### ISSUE TITLE
"Newsletter User List ID" search is not working

### ISSUE THREAD

**Issue by leandrofg** [sendgrid/eventkit-rails#10]
I have tested with a bunch of ids and I only got an error code 500:
"Error while processing route: detailedSearchResults Internal Server Error Error: Internal"

Can someone help?

**Comment by scottkawai** [comment]
Hey there - thanks for pointing that out. It looks like it was an issue with the field name used for the user list ID.  It's been updated and fixed in version 1.1.2.
