### ISSUE TITLE
Succesfully tried the integration tool just once

### ISSUE THREAD

**Issue by jalagrange** [sendgrid/eventkit-rails#9]
I succesfully tested my sendgrid integration once during the setup of the app. However once I was logged in and everything was setup, I haven't been able to do a second successfull event notification test and keep getting a 401 from Sendgrid's Event Notification app settings.

UPDATE>>>>>>>>

My eventkit-rails app on Heroku is actually receiving all notifications however its not writing to the DB given it's returning a Completed 401 Unauthorized in 179ms

**Comment by scottkawai** [comment]
Hi there,

There is an existing problem with the "Test Your Integration" button and HTTP Basic Auth (see issue #3) that would result in 401 errors.  Actual event POSTs, though, go through fine.  Are your normal events showing up?  If not, reach out to support at support.sendgrid.com so that they can take a look at your account.

**Comment by jalagrange** [comment]
Im looking at my eventkit log and sendgrid correctly sends the events to my app. However upon receiving it, my eventkit app returns a 401 and does not save anything in the DB

**Comment by scottkawai** [comment]
Got it - shoot an email to support@sendgrid.com with your SendGrid account username so that we can take a look at a few things on the account.

**Comment by jalagrange** [comment]
Sure thing, il keep you updated

**Comment by scottkawai** [comment]
Looks like we got this sorted out in the ticket and was related to the "Test Your Integration" button (similar to issue #3).

**Comment by ericpeters0n** [comment]
@jalagrange @scottkawai 
What was the solution here, please? Seeing the same :header_check issue preventing Eventkit from recording events as sent from the Sendgrid Heroku add-on (not the "Test Integration" button)

**Comment by hadifarnoud** [comment]
please advice how to fix it
